export { default as System} from './System'
export { default as Login } from './Login'
export { default as CreateAirport } from './CreateAirport'
export { default as Airlines } from './Airlines'
export { default as Dashboard } from './Dashboard'
export { default as FlightManager } from './FlightManager'